
import {Entity, PrimaryColumn, Column} from "typeorm";

@Entity("collections")
export default class Collection {
  /** the collection's site-wide identifier, generated by itch.io */
  @PrimaryColumn("int")
  id: number;

  /** the collection's title */
  @Column("text", {nullable: true})
  title: string;

  /** the date the collection was first created at */
  @Column("datetime", {nullable: true})
  createdAt: Date;

  /** the date the collection was last updated at (description, contents, etc.) */
  @Column("datetime", {nullable: true})
  updatedAt: Date;

  /** the total number of games in that collection */
  @Column("int", {nullable: true})
  gamesCount: number;

  /** the list of identifiers for games that belong to that collection */
  @Column("json", {nullable: true})
  gameIds: string;

  /**  */
  @Column("int")
  userId: number;
}
