import { Model, ColumnType } from "../model";
import { JSONField } from "../json-field";
import { DateTimeField } from "../datetime-field";

type CollectionColumns = { [K in keyof ICollection]: ColumnType };

export const CollectionModel: Model = {
  table: "collections",
  primaryKey: "id",
  columns: {
    id: ColumnType.Integer,

    title: ColumnType.Text,
    userId: ColumnType.Integer,

    createdAt: ColumnType.DateTime,
    updatedAt: ColumnType.DateTime,

    gamesCount: ColumnType.Integer,
    gameIds: ColumnType.JSON,
  } as CollectionColumns,
};

export interface ICollection {
  /** the collection's site-wide identifier, generated by itch.io */
  id: number;

  /** the collection's title */
  title: string;

  /** the date the collection was first created at */
  createdAt: DateTimeField;

  /** the date the collection was last updated at (description, contents, etc.) */
  updatedAt: DateTimeField;

  /** the total number of games in that collection */
  gamesCount: number;

  /** the list of identifiers for games that belong to that collection */
  gameIds: JSONField;

  /** the creator of this collection */
  userId: number;
}
