import { Model, ColumnType } from "../model";

type UserColumns = { [K in keyof IOwnUser]: ColumnType };

export const UserModel: Model = {
  table: "users",
  primaryKey: "id",
  columns: {
    id: ColumnType.Text,

    username: ColumnType.Text,
    displayName: ColumnType.Text,
    developer: ColumnType.Boolean,
    pressUser: ColumnType.Boolean,

    url: ColumnType.Text,
    coverUrl: ColumnType.Text,
    stillCoverUrl: ColumnType.Text,
  } as UserColumns,
};

export interface IUser {
  /* site-wide unique identifier generated by itch.io */
  id: number;

  /** the user's username */
  username: string;

  /** the user's display name */
  displayName: string;

  /** the canonical address of the game's page */
  url: string;

  /** user's avatar, may be a gif */
  coverUrl: string;

  /** user's avatar static version, only if coverUrl is a gif */
  stillCoverUrl: string;
}

export interface IOwnUser extends IUser {
  /**
   * if set, user owns press account.
   * note to reader: don't bother faking it locally — the server won't let you download
   * anything if you don't actually have a press account. Or maybe you're just looking for
   * fun errors, in which case, go ahead!
   */
  pressUser?: boolean;

  /** if set, user has expressed interest in publishing content on itch.io */
  developer?: boolean;
}
