
import {Entity, PrimaryColumn, Column} from "typeorm";

@Entity("users")
export default class User {
  @PrimaryColumn("int")
  /* site-wide unique identifier generated by itch.io */
  id: number;

  @Column("text", {nullable: true})
  /** the user's username */
  username: string;

  @Column("text", {nullable: true})
  /** the canonical address of the game's page */
  url: string;

  @Column("text", {nullable: true})
  coverUrl: string;

  @Column("text", {nullable: true})
  stillCoverUrl: string;
}
