import { Model, ensureExtends, Column } from "../model";

const UserModelOriginal = {
  table: "users",
  primaryKey: "id",
  columns: {
    id: Column.Integer,

    username: Column.Text,
    displayName: Column.Text,
    developer: Column.Boolean,
    pressUser: Column.Boolean,

    url: Column.Text,
    coverUrl: Column.Text,
    stillCoverUrl: Column.Text,
  },
};

export const UserModel: Model = UserModelOriginal;

type Columns = { [K in keyof typeof UserModelOriginal.columns]: any };
ensureExtends<Columns, IOwnUser>();
ensureExtends<IOwnUser, Columns>();

export interface IUser {
  /* site-wide unique identifier generated by itch.io */
  id: number;

  /** the user's username */
  username: string;

  /** the user's display name */
  displayName: string;

  /** the canonical address of the game's page */
  url: string;

  /** user's avatar, may be a gif */
  coverUrl: string;

  /** user's avatar static version, only if coverUrl is a gif */
  stillCoverUrl: string;
}

export interface IOwnUser extends IUser {
  /**
   * if set, user owns press account.
   * note to reader: don't bother faking it locally — the server won't let you download
   * anything if you don't actually have a press account. Or maybe you're just looking for
   * fun errors, in which case, go ahead!
   */
  pressUser: boolean;

  /** if set, user has expressed interest in publishing content on itch.io */
  developer: boolean;
}
