// automatically generated by the FlatBuffers compiler, do not modify

import { flatbuffers } from "./flatbuffers"
/**
 * @enum
 */
export namespace capsule.messages{
export enum PixFmt{
  UNKNOWN= 0,
  RGBA= 40069,
  BGRA= 40070,
  RGB10_A2= 40071,
  YUV444P= 60021
}};

/**
 * @enum
 */
export namespace capsule.messages{
export enum Message{
  NONE= 0,
  HotkeyPressed= 1,
  CaptureStart= 2,
  CaptureStop= 3,
  VideoSetup= 4,
  VideoFrameCommitted= 5,
  VideoFrameProcessed= 6
}};

/**
 * @constructor
 */
export namespace capsule.messages{
export class Packet {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  bb: flatbuffers.ByteBuffer= null;

  /**
   * @type {number}
   */
  bb_pos:number = 0;
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Packet}
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Packet {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Packet=} obj
 * @returns {Packet}
 */
static getRootAsPacket(bb:flatbuffers.ByteBuffer, obj?:Packet):Packet {
  return (obj || new Packet).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {capsule.messages.Message}
 */
messageType():capsule.messages.Message {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? /** @type {capsule.messages.Message} */ (this.bb.readUint8(this.bb_pos + offset)) : capsule.messages.Message.NONE;
};

/**
 * @param {flatbuffers.Table} obj
 * @returns {?flatbuffers.Table}
 */
message<T extends flatbuffers.Table>(obj:T):T {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
static startPacket(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {capsule.messages.Message} messageType
 */
static addMessageType(builder:flatbuffers.Builder, messageType:capsule.messages.Message) {
  builder.addFieldInt8(0, messageType, capsule.messages.Message.NONE);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} messageOffset
 */
static addMessage(builder:flatbuffers.Builder, messageOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, messageOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
static endPacket(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
static finishPacketBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
};

}
}
/**
 * @constructor
 */
export namespace capsule.messages{
export class HotkeyPressed {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  bb: flatbuffers.ByteBuffer= null;

  /**
   * @type {number}
   */
  bb_pos:number = 0;
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {HotkeyPressed}
 */
__init(i:number, bb:flatbuffers.ByteBuffer):HotkeyPressed {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {HotkeyPressed=} obj
 * @returns {HotkeyPressed}
 */
static getRootAsHotkeyPressed(bb:flatbuffers.ByteBuffer, obj?:HotkeyPressed):HotkeyPressed {
  return (obj || new HotkeyPressed).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Builder} builder
 */
static startHotkeyPressed(builder:flatbuffers.Builder) {
  builder.startObject(0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
static endHotkeyPressed(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

}
}
/**
 * @constructor
 */
export namespace capsule.messages{
export class CaptureStart {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  bb: flatbuffers.ByteBuffer= null;

  /**
   * @type {number}
   */
  bb_pos:number = 0;
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {CaptureStart}
 */
__init(i:number, bb:flatbuffers.ByteBuffer):CaptureStart {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {CaptureStart=} obj
 * @returns {CaptureStart}
 */
static getRootAsCaptureStart(bb:flatbuffers.ByteBuffer, obj?:CaptureStart):CaptureStart {
  return (obj || new CaptureStart).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
fps():number {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
sizeDivider():number {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {boolean}
 */
gpuColorConv():boolean {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @param {flatbuffers.Builder} builder
 */
static startCaptureStart(builder:flatbuffers.Builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} fps
 */
static addFps(builder:flatbuffers.Builder, fps:number) {
  builder.addFieldInt32(0, fps, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} sizeDivider
 */
static addSizeDivider(builder:flatbuffers.Builder, sizeDivider:number) {
  builder.addFieldInt32(1, sizeDivider, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} gpuColorConv
 */
static addGpuColorConv(builder:flatbuffers.Builder, gpuColorConv:boolean) {
  builder.addFieldInt8(2, +gpuColorConv, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
static endCaptureStart(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

}
}
/**
 * @constructor
 */
export namespace capsule.messages{
export class CaptureStop {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  bb: flatbuffers.ByteBuffer= null;

  /**
   * @type {number}
   */
  bb_pos:number = 0;
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {CaptureStop}
 */
__init(i:number, bb:flatbuffers.ByteBuffer):CaptureStop {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {CaptureStop=} obj
 * @returns {CaptureStop}
 */
static getRootAsCaptureStop(bb:flatbuffers.ByteBuffer, obj?:CaptureStop):CaptureStop {
  return (obj || new CaptureStop).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Builder} builder
 */
static startCaptureStop(builder:flatbuffers.Builder) {
  builder.startObject(0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
static endCaptureStop(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

}
}
/**
 * @constructor
 */
export namespace capsule.messages{
export class VideoSetup {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  bb: flatbuffers.ByteBuffer= null;

  /**
   * @type {number}
   */
  bb_pos:number = 0;
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {VideoSetup}
 */
__init(i:number, bb:flatbuffers.ByteBuffer):VideoSetup {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {VideoSetup=} obj
 * @returns {VideoSetup}
 */
static getRootAsVideoSetup(bb:flatbuffers.ByteBuffer, obj?:VideoSetup):VideoSetup {
  return (obj || new VideoSetup).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
width():number {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
height():number {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {capsule.messages.PixFmt}
 */
pixFmt():capsule.messages.PixFmt {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? /** @type {capsule.messages.PixFmt} */ (this.bb.readInt32(this.bb_pos + offset)) : capsule.messages.PixFmt.UNKNOWN;
};

/**
 * @returns {boolean}
 */
vflip():boolean {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @param {number} index
 * @returns {flatbuffers.Long}
 */
offset(index: number):flatbuffers.Long {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.readInt64(this.bb.__vector(this.bb_pos + offset) + index * 8) : this.bb.createLong(0, 0);
};

/**
 * @returns {number}
 */
offsetLength():number {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {number} index
 * @returns {flatbuffers.Long}
 */
linesize(index: number):flatbuffers.Long {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.readInt64(this.bb.__vector(this.bb_pos + offset) + index * 8) : this.bb.createLong(0, 0);
};

/**
 * @returns {number}
 */
linesizeLength():number {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {capsule.messages.Shmem=} obj
 * @returns {capsule.messages.Shmem}
 */
shmem(obj?:capsule.messages.Shmem):capsule.messages.Shmem {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? (obj || new capsule.messages.Shmem).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
static startVideoSetup(builder:flatbuffers.Builder) {
  builder.startObject(7);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} width
 */
static addWidth(builder:flatbuffers.Builder, width:number) {
  builder.addFieldInt32(0, width, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} height
 */
static addHeight(builder:flatbuffers.Builder, height:number) {
  builder.addFieldInt32(1, height, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {capsule.messages.PixFmt} pixFmt
 */
static addPixFmt(builder:flatbuffers.Builder, pixFmt:capsule.messages.PixFmt) {
  builder.addFieldInt32(2, pixFmt, capsule.messages.PixFmt.UNKNOWN);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} vflip
 */
static addVflip(builder:flatbuffers.Builder, vflip:boolean) {
  builder.addFieldInt8(3, +vflip, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offsetOffset
 */
static addOffset(builder:flatbuffers.Builder, offsetOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, offsetOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Long>} data
 * @returns {flatbuffers.Offset}
 */
static createOffsetVector(builder:flatbuffers.Builder, data:flatbuffers.Long[]):flatbuffers.Offset {
if(!data){
  return null
}
  builder.startVector(8, data.length, 8);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt64(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
static startOffsetVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(8, numElems, 8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} linesizeOffset
 */
static addLinesize(builder:flatbuffers.Builder, linesizeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, linesizeOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Long>} data
 * @returns {flatbuffers.Offset}
 */
static createLinesizeVector(builder:flatbuffers.Builder, data:flatbuffers.Long[]):flatbuffers.Offset {
if(!data){
  return null
}
  builder.startVector(8, data.length, 8);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt64(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
static startLinesizeVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(8, numElems, 8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} shmemOffset
 */
static addShmem(builder:flatbuffers.Builder, shmemOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, shmemOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
static endVideoSetup(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

}
}
/**
 * @constructor
 */
export namespace capsule.messages{
export class Shmem {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  bb: flatbuffers.ByteBuffer= null;

  /**
   * @type {number}
   */
  bb_pos:number = 0;
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Shmem}
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Shmem {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Shmem=} obj
 * @returns {Shmem}
 */
static getRootAsShmem(bb:flatbuffers.ByteBuffer, obj?:Shmem):Shmem {
  return (obj || new Shmem).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
path():string
path(optionalEncoding:flatbuffers.Encoding):string|Uint8Array
path(optionalEncoding?:any):string|Uint8Array {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {flatbuffers.Long}
 */
size():flatbuffers.Long {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 */
static startShmem(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} pathOffset
 */
static addPath(builder:flatbuffers.Builder, pathOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, pathOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} size
 */
static addSize(builder:flatbuffers.Builder, size:flatbuffers.Long) {
  builder.addFieldInt64(1, size, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
static endShmem(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

}
}
/**
 * @constructor
 */
export namespace capsule.messages{
export class VideoFrameCommitted {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  bb: flatbuffers.ByteBuffer= null;

  /**
   * @type {number}
   */
  bb_pos:number = 0;
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {VideoFrameCommitted}
 */
__init(i:number, bb:flatbuffers.ByteBuffer):VideoFrameCommitted {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {VideoFrameCommitted=} obj
 * @returns {VideoFrameCommitted}
 */
static getRootAsVideoFrameCommitted(bb:flatbuffers.ByteBuffer, obj?:VideoFrameCommitted):VideoFrameCommitted {
  return (obj || new VideoFrameCommitted).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {flatbuffers.Long}
 */
timestamp():flatbuffers.Long {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {number}
 */
index():number {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
static startVideoFrameCommitted(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} timestamp
 */
static addTimestamp(builder:flatbuffers.Builder, timestamp:flatbuffers.Long) {
  builder.addFieldInt64(0, timestamp, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} index
 */
static addIndex(builder:flatbuffers.Builder, index:number) {
  builder.addFieldInt32(1, index, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
static endVideoFrameCommitted(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

}
}
/**
 * @constructor
 */
export namespace capsule.messages{
export class VideoFrameProcessed {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  bb: flatbuffers.ByteBuffer= null;

  /**
   * @type {number}
   */
  bb_pos:number = 0;
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {VideoFrameProcessed}
 */
__init(i:number, bb:flatbuffers.ByteBuffer):VideoFrameProcessed {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {VideoFrameProcessed=} obj
 * @returns {VideoFrameProcessed}
 */
static getRootAsVideoFrameProcessed(bb:flatbuffers.ByteBuffer, obj?:VideoFrameProcessed):VideoFrameProcessed {
  return (obj || new VideoFrameProcessed).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
index():number {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
static startVideoFrameProcessed(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} index
 */
static addIndex(builder:flatbuffers.Builder, index:number) {
  builder.addFieldInt32(0, index, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
static endVideoFrameProcessed(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

}
}
