import { Watcher } from "common/util/watcher";

import preboot from "./preboot";
import preferences from "./preferences";
import mainWindow from "./main-window";
import locales from "./locales";
import tray from "./tray";
import menu from "./menu";
import installLocations from "./install-locations";
import selfUpdate from "./self-update";
import setup from "./setup";
import tabs from "./tabs";
import triggers from "./triggers";
import modals from "./modals";
import openAtLogin from "./open-at-login";
import proxy from "./proxy";
import login from "./login";
import dialogs from "./dialogs";
import i18n from "./i18n";
import contextMenu from "./context-menu";
import profile from "./profile";
import navigation from "./navigation";
import tabSave from "./tab-save";
import commons from "./commons";
import purchases from "./purchases";
import url from "./url";
import itchInternal from "./itch-internal";
import tasks from "./tasks";
import downloads from "./downloads";
import queueLaunch from "./queue-launch";
import updater from "./updater";
import gameUpdates from "./game-updates";
import search from "./search";
import webContents from "./web-contents";
import notifications from "./notifications";
import clipboard from "./clipboard";

import { currentRuntime } from "../os/runtime";
const runtime = currentRuntime();

export default function getWatcher() {
  const watcher = new Watcher();

  preboot(watcher);
  preferences(watcher);
  mainWindow(watcher);
  locales(watcher);
  tray(watcher);
  menu(watcher, runtime);
  installLocations(watcher);
  selfUpdate(watcher);
  setup(watcher);
  tabs(watcher);
  triggers(watcher);
  modals(watcher);
  openAtLogin(watcher);
  proxy(watcher);
  login(watcher);
  dialogs(watcher);
  i18n(watcher);
  contextMenu(watcher);
  profile(watcher);
  navigation(watcher);
  tabSave(watcher);
  commons(watcher);
  purchases(watcher);
  url(watcher);
  itchInternal(watcher);
  tasks(watcher);
  downloads(watcher);
  queueLaunch(watcher);
  updater(watcher);
  gameUpdates(watcher);
  search(watcher);
  webContents(watcher);
  notifications(watcher);
  clipboard(watcher);

  watcher.validate();
  return watcher;
}
