import { GameClassification } from "common/butlerd/messages";

const validClassifications = new Set<string>(Object.values(GameClassification));

/**
 * Narrows a raw query-param string down to a GameClassification.
 * Classification query params are generated by app-internal links, so in
 * practice they're either absent or valid; anything else (a hand-crafted
 * url) is treated as "no filter".
 */
export function classificationFromQuery(
  raw: string | undefined
): GameClassification | undefined {
  if (raw && validClassifications.has(raw)) {
    return raw as GameClassification;
  }
  return undefined;
}
