
import {Watcher} from "./watcher";

import preboot from "./preboot";
import preferences from "./preferences";
import login from "./login";
import market from "./market";
import mainWindow from "./main-window";
import fetch from "./fetch";
import i18n from "./i18n";
import locales from "./locales";
import rememberedSessions from "./remembered-sessions";
import session from "./session";
import url from "./url";
import tray from "./tray";
import notifications from "./notifications";
import menu from "./menu";
import installLocations from "./install-locations";
import purchases from "./purchases";
import selfUpdate from "./self-update";
import setup from "./setup";
import updater from "./updater";
import tabs from "./tabs";
import triggers from "./triggers";
import contextMenu from "./context-menu";
import share from "./share";
import navigation from "./navigation";
import clipboard from "./clipboard";
import tasks from "./tasks";
import dialogs from "./dialogs";
import report from "./report";
import perf from "./perf";
import modals from "./modals";
import openAtLogin from "./open-at-login";
import gameUpdates from "./game-updates";
import proxy from "./proxy";

let watcher = new Watcher();
preboot(watcher);
preferences(watcher);
login(watcher);
market(watcher);
mainWindow(watcher);
fetch(watcher);
i18n(watcher);
locales(watcher);
rememberedSessions(watcher);
session(watcher);
url(watcher);
tray(watcher);
notifications(watcher);
menu(watcher);
installLocations(watcher);
purchases(watcher);
selfUpdate(watcher);
setup(watcher);
updater(watcher);
tabs(watcher);
triggers(watcher);
contextMenu(watcher);
share(watcher);
navigation(watcher);
clipboard(watcher);
tasks(watcher);
dialogs(watcher);
report(watcher);
perf(watcher);
modals(watcher);
openAtLogin(watcher);
gameUpdates(watcher);
proxy(watcher);

watcher.validate();

export default watcher;
