// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/proxyquire/proxyquire.d.ts
interface Proxyquire {

    (request: string, stubs: any): any;
    <T>(request: string, stubs: any): T;

    load(request: string, stubs: any): any;
    load<T>(request: string, stubs: any): T;

    noCallThru(): Proxyquire;
    callThru(): Proxyquire;

    noPreserveCache(): Proxyquire;
    preserveCache(): Proxyquire;
}

declare module 'proxyquire' {

    var p: Proxyquire;
    export = p;
}
