.TH "ITCH" "6" "APRIL 2016"
.SH NAME
.PP
itch \- install and play itch.io games easily
.SH DESCRIPTION
.PP
The goal of this project is to give you a desktop application that you can
download and run games from itch.io with.
Additionally you should be able to update games and get notified when games are updated.
The goal is not to replace the itch.io website.
.SH SUPPORT
.I https://github.com/itchio/itch/issues
.SH COPYRIGHT
Copyright \(co 2015\-2016 Itch Corp
