// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var capsule = capsule || {};

/**
 * @const
 * @namespace
 */
capsule.messages = capsule.messages || {};

/**
 * @enum
 */
capsule.messages.PixFmt = {
  UNKNOWN: 0,
  RGBA: 40069,
  BGRA: 40070,
  RGB10_A2: 40071,
  YUV444P: 60021
};

/**
 * @enum
 */
capsule.messages.Message = {
  NONE: 0,
  HotkeyPressed: 1,
  CaptureStart: 2,
  CaptureStop: 3,
  VideoSetup: 4,
  VideoFrameCommitted: 5,
  VideoFrameProcessed: 6
};

/**
 * @constructor
 */
capsule.messages.Packet = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {capsule.messages.Packet}
 */
capsule.messages.Packet.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {capsule.messages.Packet=} obj
 * @returns {capsule.messages.Packet}
 */
capsule.messages.Packet.getRootAsPacket = function(bb, obj) {
  return (obj || new capsule.messages.Packet).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {capsule.messages.Message}
 */
capsule.messages.Packet.prototype.messageType = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? /** @type {capsule.messages.Message} */ (this.bb.readUint8(this.bb_pos + offset)) : capsule.messages.Message.NONE;
};

/**
 * @param {flatbuffers.Table} obj
 * @returns {?flatbuffers.Table}
 */
capsule.messages.Packet.prototype.message = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
capsule.messages.Packet.startPacket = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {capsule.messages.Message} messageType
 */
capsule.messages.Packet.addMessageType = function(builder, messageType) {
  builder.addFieldInt8(0, messageType, capsule.messages.Message.NONE);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} messageOffset
 */
capsule.messages.Packet.addMessage = function(builder, messageOffset) {
  builder.addFieldOffset(1, messageOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
capsule.messages.Packet.endPacket = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
capsule.messages.Packet.finishPacketBuffer = function(builder, offset) {
  builder.finish(offset);
};

/**
 * @constructor
 */
capsule.messages.HotkeyPressed = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {capsule.messages.HotkeyPressed}
 */
capsule.messages.HotkeyPressed.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {capsule.messages.HotkeyPressed=} obj
 * @returns {capsule.messages.HotkeyPressed}
 */
capsule.messages.HotkeyPressed.getRootAsHotkeyPressed = function(bb, obj) {
  return (obj || new capsule.messages.HotkeyPressed).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Builder} builder
 */
capsule.messages.HotkeyPressed.startHotkeyPressed = function(builder) {
  builder.startObject(0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
capsule.messages.HotkeyPressed.endHotkeyPressed = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
capsule.messages.CaptureStart = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {capsule.messages.CaptureStart}
 */
capsule.messages.CaptureStart.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {capsule.messages.CaptureStart=} obj
 * @returns {capsule.messages.CaptureStart}
 */
capsule.messages.CaptureStart.getRootAsCaptureStart = function(bb, obj) {
  return (obj || new capsule.messages.CaptureStart).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
capsule.messages.CaptureStart.prototype.fps = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
capsule.messages.CaptureStart.prototype.sizeDivider = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {boolean}
 */
capsule.messages.CaptureStart.prototype.gpuColorConv = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @param {flatbuffers.Builder} builder
 */
capsule.messages.CaptureStart.startCaptureStart = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} fps
 */
capsule.messages.CaptureStart.addFps = function(builder, fps) {
  builder.addFieldInt32(0, fps, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} sizeDivider
 */
capsule.messages.CaptureStart.addSizeDivider = function(builder, sizeDivider) {
  builder.addFieldInt32(1, sizeDivider, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} gpuColorConv
 */
capsule.messages.CaptureStart.addGpuColorConv = function(builder, gpuColorConv) {
  builder.addFieldInt8(2, +gpuColorConv, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
capsule.messages.CaptureStart.endCaptureStart = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
capsule.messages.CaptureStop = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {capsule.messages.CaptureStop}
 */
capsule.messages.CaptureStop.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {capsule.messages.CaptureStop=} obj
 * @returns {capsule.messages.CaptureStop}
 */
capsule.messages.CaptureStop.getRootAsCaptureStop = function(bb, obj) {
  return (obj || new capsule.messages.CaptureStop).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Builder} builder
 */
capsule.messages.CaptureStop.startCaptureStop = function(builder) {
  builder.startObject(0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
capsule.messages.CaptureStop.endCaptureStop = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
capsule.messages.VideoSetup = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {capsule.messages.VideoSetup}
 */
capsule.messages.VideoSetup.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {capsule.messages.VideoSetup=} obj
 * @returns {capsule.messages.VideoSetup}
 */
capsule.messages.VideoSetup.getRootAsVideoSetup = function(bb, obj) {
  return (obj || new capsule.messages.VideoSetup).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
capsule.messages.VideoSetup.prototype.width = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
capsule.messages.VideoSetup.prototype.height = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {capsule.messages.PixFmt}
 */
capsule.messages.VideoSetup.prototype.pixFmt = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? /** @type {capsule.messages.PixFmt} */ (this.bb.readInt32(this.bb_pos + offset)) : capsule.messages.PixFmt.UNKNOWN;
};

/**
 * @returns {boolean}
 */
capsule.messages.VideoSetup.prototype.vflip = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @param {number} index
 * @returns {flatbuffers.Long}
 */
capsule.messages.VideoSetup.prototype.offset = function(index) {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.readInt64(this.bb.__vector(this.bb_pos + offset) + index * 8) : this.bb.createLong(0, 0);
};

/**
 * @returns {number}
 */
capsule.messages.VideoSetup.prototype.offsetLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {number} index
 * @returns {flatbuffers.Long}
 */
capsule.messages.VideoSetup.prototype.linesize = function(index) {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.readInt64(this.bb.__vector(this.bb_pos + offset) + index * 8) : this.bb.createLong(0, 0);
};

/**
 * @returns {number}
 */
capsule.messages.VideoSetup.prototype.linesizeLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {capsule.messages.Shmem=} obj
 * @returns {capsule.messages.Shmem}
 */
capsule.messages.VideoSetup.prototype.shmem = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? (obj || new capsule.messages.Shmem).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
capsule.messages.VideoSetup.startVideoSetup = function(builder) {
  builder.startObject(7);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} width
 */
capsule.messages.VideoSetup.addWidth = function(builder, width) {
  builder.addFieldInt32(0, width, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} height
 */
capsule.messages.VideoSetup.addHeight = function(builder, height) {
  builder.addFieldInt32(1, height, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {capsule.messages.PixFmt} pixFmt
 */
capsule.messages.VideoSetup.addPixFmt = function(builder, pixFmt) {
  builder.addFieldInt32(2, pixFmt, capsule.messages.PixFmt.UNKNOWN);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} vflip
 */
capsule.messages.VideoSetup.addVflip = function(builder, vflip) {
  builder.addFieldInt8(3, +vflip, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offsetOffset
 */
capsule.messages.VideoSetup.addOffset = function(builder, offsetOffset) {
  builder.addFieldOffset(4, offsetOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Long>} data
 * @returns {flatbuffers.Offset}
 */
capsule.messages.VideoSetup.createOffsetVector = function(builder, data) {
  builder.startVector(8, data.length, 8);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt64(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
capsule.messages.VideoSetup.startOffsetVector = function(builder, numElems) {
  builder.startVector(8, numElems, 8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} linesizeOffset
 */
capsule.messages.VideoSetup.addLinesize = function(builder, linesizeOffset) {
  builder.addFieldOffset(5, linesizeOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Long>} data
 * @returns {flatbuffers.Offset}
 */
capsule.messages.VideoSetup.createLinesizeVector = function(builder, data) {
  builder.startVector(8, data.length, 8);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt64(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
capsule.messages.VideoSetup.startLinesizeVector = function(builder, numElems) {
  builder.startVector(8, numElems, 8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} shmemOffset
 */
capsule.messages.VideoSetup.addShmem = function(builder, shmemOffset) {
  builder.addFieldOffset(6, shmemOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
capsule.messages.VideoSetup.endVideoSetup = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
capsule.messages.Shmem = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {capsule.messages.Shmem}
 */
capsule.messages.Shmem.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {capsule.messages.Shmem=} obj
 * @returns {capsule.messages.Shmem}
 */
capsule.messages.Shmem.getRootAsShmem = function(bb, obj) {
  return (obj || new capsule.messages.Shmem).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
capsule.messages.Shmem.prototype.path = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {flatbuffers.Long}
 */
capsule.messages.Shmem.prototype.size = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 */
capsule.messages.Shmem.startShmem = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} pathOffset
 */
capsule.messages.Shmem.addPath = function(builder, pathOffset) {
  builder.addFieldOffset(0, pathOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} size
 */
capsule.messages.Shmem.addSize = function(builder, size) {
  builder.addFieldInt64(1, size, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
capsule.messages.Shmem.endShmem = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
capsule.messages.VideoFrameCommitted = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {capsule.messages.VideoFrameCommitted}
 */
capsule.messages.VideoFrameCommitted.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {capsule.messages.VideoFrameCommitted=} obj
 * @returns {capsule.messages.VideoFrameCommitted}
 */
capsule.messages.VideoFrameCommitted.getRootAsVideoFrameCommitted = function(bb, obj) {
  return (obj || new capsule.messages.VideoFrameCommitted).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {flatbuffers.Long}
 */
capsule.messages.VideoFrameCommitted.prototype.timestamp = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {number}
 */
capsule.messages.VideoFrameCommitted.prototype.index = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
capsule.messages.VideoFrameCommitted.startVideoFrameCommitted = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} timestamp
 */
capsule.messages.VideoFrameCommitted.addTimestamp = function(builder, timestamp) {
  builder.addFieldInt64(0, timestamp, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} index
 */
capsule.messages.VideoFrameCommitted.addIndex = function(builder, index) {
  builder.addFieldInt32(1, index, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
capsule.messages.VideoFrameCommitted.endVideoFrameCommitted = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
capsule.messages.VideoFrameProcessed = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {capsule.messages.VideoFrameProcessed}
 */
capsule.messages.VideoFrameProcessed.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {capsule.messages.VideoFrameProcessed=} obj
 * @returns {capsule.messages.VideoFrameProcessed}
 */
capsule.messages.VideoFrameProcessed.getRootAsVideoFrameProcessed = function(bb, obj) {
  return (obj || new capsule.messages.VideoFrameProcessed).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
capsule.messages.VideoFrameProcessed.prototype.index = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
capsule.messages.VideoFrameProcessed.startVideoFrameProcessed = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} index
 */
capsule.messages.VideoFrameProcessed.addIndex = function(builder, index) {
  builder.addFieldInt32(0, index, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
capsule.messages.VideoFrameProcessed.endVideoFrameProcessed = function(builder) {
  var offset = builder.endObject();
  return offset;
};

// Exports for Node.js and RequireJS
this.capsule = capsule;
