// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var Capsule = Capsule || {};

/**
 * @const
 * @namespace
 */
Capsule.Messages = Capsule.Messages || {};

/**
 * @enum
 */
Capsule.Messages.PixFmt = {
  UNKNOWN: 0,
  RGBA: 40069,
  BGRA: 40070,
  RGB10_A2: 40071,
  YUV444P: 60021
};

/**
 * @enum
 */
Capsule.Messages.Message = {
  NONE: 0,
  CaptureStart: 1,
  CaptureStop: 2,
  VideoSetup: 3,
  VideoFrameCommitted: 4,
  VideoFrameProcessed: 5
};

/**
 * @constructor
 */
Capsule.Messages.Packet = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Capsule.Messages.Packet}
 */
Capsule.Messages.Packet.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Capsule.Messages.Packet=} obj
 * @returns {Capsule.Messages.Packet}
 */
Capsule.Messages.Packet.getRootAsPacket = function(bb, obj) {
  return (obj || new Capsule.Messages.Packet).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {Capsule.Messages.Message}
 */
Capsule.Messages.Packet.prototype.messageType = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? /** @type {Capsule.Messages.Message} */ (this.bb.readUint8(this.bb_pos + offset)) : Capsule.Messages.Message.NONE;
};

/**
 * @param {flatbuffers.Table} obj
 * @returns {?flatbuffers.Table}
 */
Capsule.Messages.Packet.prototype.message = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
Capsule.Messages.Packet.startPacket = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Capsule.Messages.Message} messageType
 */
Capsule.Messages.Packet.addMessageType = function(builder, messageType) {
  builder.addFieldInt8(0, messageType, Capsule.Messages.Message.NONE);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} messageOffset
 */
Capsule.Messages.Packet.addMessage = function(builder, messageOffset) {
  builder.addFieldOffset(1, messageOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
Capsule.Messages.Packet.endPacket = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
Capsule.Messages.Packet.finishPacketBuffer = function(builder, offset) {
  builder.finish(offset);
};

/**
 * @constructor
 */
Capsule.Messages.CaptureStart = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Capsule.Messages.CaptureStart}
 */
Capsule.Messages.CaptureStart.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Capsule.Messages.CaptureStart=} obj
 * @returns {Capsule.Messages.CaptureStart}
 */
Capsule.Messages.CaptureStart.getRootAsCaptureStart = function(bb, obj) {
  return (obj || new Capsule.Messages.CaptureStart).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
Capsule.Messages.CaptureStart.prototype.fps = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
Capsule.Messages.CaptureStart.prototype.sizeDivider = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {boolean}
 */
Capsule.Messages.CaptureStart.prototype.gpuColorConv = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @param {flatbuffers.Builder} builder
 */
Capsule.Messages.CaptureStart.startCaptureStart = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} fps
 */
Capsule.Messages.CaptureStart.addFps = function(builder, fps) {
  builder.addFieldInt32(0, fps, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} sizeDivider
 */
Capsule.Messages.CaptureStart.addSizeDivider = function(builder, sizeDivider) {
  builder.addFieldInt32(1, sizeDivider, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} gpuColorConv
 */
Capsule.Messages.CaptureStart.addGpuColorConv = function(builder, gpuColorConv) {
  builder.addFieldInt8(2, +gpuColorConv, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
Capsule.Messages.CaptureStart.endCaptureStart = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
Capsule.Messages.CaptureStop = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Capsule.Messages.CaptureStop}
 */
Capsule.Messages.CaptureStop.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Capsule.Messages.CaptureStop=} obj
 * @returns {Capsule.Messages.CaptureStop}
 */
Capsule.Messages.CaptureStop.getRootAsCaptureStop = function(bb, obj) {
  return (obj || new Capsule.Messages.CaptureStop).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Builder} builder
 */
Capsule.Messages.CaptureStop.startCaptureStop = function(builder) {
  builder.startObject(0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
Capsule.Messages.CaptureStop.endCaptureStop = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
Capsule.Messages.VideoSetup = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Capsule.Messages.VideoSetup}
 */
Capsule.Messages.VideoSetup.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Capsule.Messages.VideoSetup=} obj
 * @returns {Capsule.Messages.VideoSetup}
 */
Capsule.Messages.VideoSetup.getRootAsVideoSetup = function(bb, obj) {
  return (obj || new Capsule.Messages.VideoSetup).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
Capsule.Messages.VideoSetup.prototype.width = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
Capsule.Messages.VideoSetup.prototype.height = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {Capsule.Messages.PixFmt}
 */
Capsule.Messages.VideoSetup.prototype.pixFmt = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? /** @type {Capsule.Messages.PixFmt} */ (this.bb.readInt32(this.bb_pos + offset)) : Capsule.Messages.PixFmt.UNKNOWN;
};

/**
 * @returns {boolean}
 */
Capsule.Messages.VideoSetup.prototype.vflip = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @param {number} index
 * @returns {number}
 */
Capsule.Messages.VideoSetup.prototype.offset = function(index) {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.readUint32(this.bb.__vector(this.bb_pos + offset) + index * 4) : 0;
};

/**
 * @returns {number}
 */
Capsule.Messages.VideoSetup.prototype.offsetLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {Uint32Array}
 */
Capsule.Messages.VideoSetup.prototype.offsetArray = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? new Uint32Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param {number} index
 * @returns {number}
 */
Capsule.Messages.VideoSetup.prototype.linesize = function(index) {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.readUint32(this.bb.__vector(this.bb_pos + offset) + index * 4) : 0;
};

/**
 * @returns {number}
 */
Capsule.Messages.VideoSetup.prototype.linesizeLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {Uint32Array}
 */
Capsule.Messages.VideoSetup.prototype.linesizeArray = function() {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? new Uint32Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param {Capsule.Messages.Shmem=} obj
 * @returns {Capsule.Messages.Shmem}
 */
Capsule.Messages.VideoSetup.prototype.shmem = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? (obj || new Capsule.Messages.Shmem).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
Capsule.Messages.VideoSetup.startVideoSetup = function(builder) {
  builder.startObject(7);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} width
 */
Capsule.Messages.VideoSetup.addWidth = function(builder, width) {
  builder.addFieldInt32(0, width, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} height
 */
Capsule.Messages.VideoSetup.addHeight = function(builder, height) {
  builder.addFieldInt32(1, height, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Capsule.Messages.PixFmt} pixFmt
 */
Capsule.Messages.VideoSetup.addPixFmt = function(builder, pixFmt) {
  builder.addFieldInt32(2, pixFmt, Capsule.Messages.PixFmt.UNKNOWN);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} vflip
 */
Capsule.Messages.VideoSetup.addVflip = function(builder, vflip) {
  builder.addFieldInt8(3, +vflip, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offsetOffset
 */
Capsule.Messages.VideoSetup.addOffset = function(builder, offsetOffset) {
  builder.addFieldOffset(4, offsetOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<number>} data
 * @returns {flatbuffers.Offset}
 */
Capsule.Messages.VideoSetup.createOffsetVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt32(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
Capsule.Messages.VideoSetup.startOffsetVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} linesizeOffset
 */
Capsule.Messages.VideoSetup.addLinesize = function(builder, linesizeOffset) {
  builder.addFieldOffset(5, linesizeOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<number>} data
 * @returns {flatbuffers.Offset}
 */
Capsule.Messages.VideoSetup.createLinesizeVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt32(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
Capsule.Messages.VideoSetup.startLinesizeVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} shmemOffset
 */
Capsule.Messages.VideoSetup.addShmem = function(builder, shmemOffset) {
  builder.addFieldOffset(6, shmemOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
Capsule.Messages.VideoSetup.endVideoSetup = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
Capsule.Messages.Shmem = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Capsule.Messages.Shmem}
 */
Capsule.Messages.Shmem.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Capsule.Messages.Shmem=} obj
 * @returns {Capsule.Messages.Shmem}
 */
Capsule.Messages.Shmem.getRootAsShmem = function(bb, obj) {
  return (obj || new Capsule.Messages.Shmem).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
Capsule.Messages.Shmem.prototype.path = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {flatbuffers.Long}
 */
Capsule.Messages.Shmem.prototype.size = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 */
Capsule.Messages.Shmem.startShmem = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} pathOffset
 */
Capsule.Messages.Shmem.addPath = function(builder, pathOffset) {
  builder.addFieldOffset(0, pathOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} size
 */
Capsule.Messages.Shmem.addSize = function(builder, size) {
  builder.addFieldInt64(1, size, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
Capsule.Messages.Shmem.endShmem = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
Capsule.Messages.VideoFrameCommitted = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Capsule.Messages.VideoFrameCommitted}
 */
Capsule.Messages.VideoFrameCommitted.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Capsule.Messages.VideoFrameCommitted=} obj
 * @returns {Capsule.Messages.VideoFrameCommitted}
 */
Capsule.Messages.VideoFrameCommitted.getRootAsVideoFrameCommitted = function(bb, obj) {
  return (obj || new Capsule.Messages.VideoFrameCommitted).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {flatbuffers.Long}
 */
Capsule.Messages.VideoFrameCommitted.prototype.timestamp = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {number}
 */
Capsule.Messages.VideoFrameCommitted.prototype.index = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
Capsule.Messages.VideoFrameCommitted.startVideoFrameCommitted = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} timestamp
 */
Capsule.Messages.VideoFrameCommitted.addTimestamp = function(builder, timestamp) {
  builder.addFieldInt64(0, timestamp, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} index
 */
Capsule.Messages.VideoFrameCommitted.addIndex = function(builder, index) {
  builder.addFieldInt32(1, index, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
Capsule.Messages.VideoFrameCommitted.endVideoFrameCommitted = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
Capsule.Messages.VideoFrameProcessed = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Capsule.Messages.VideoFrameProcessed}
 */
Capsule.Messages.VideoFrameProcessed.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Capsule.Messages.VideoFrameProcessed=} obj
 * @returns {Capsule.Messages.VideoFrameProcessed}
 */
Capsule.Messages.VideoFrameProcessed.getRootAsVideoFrameProcessed = function(bb, obj) {
  return (obj || new Capsule.Messages.VideoFrameProcessed).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
Capsule.Messages.VideoFrameProcessed.prototype.index = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
Capsule.Messages.VideoFrameProcessed.startVideoFrameProcessed = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} index
 */
Capsule.Messages.VideoFrameProcessed.addIndex = function(builder, index) {
  builder.addFieldInt32(0, index, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
Capsule.Messages.VideoFrameProcessed.endVideoFrameProcessed = function(builder) {
  var offset = builder.endObject();
  return offset;
};

// Exports for Node.js and RequireJS
this.Capsule = Capsule;
